FROM node:22-alpine

WORKDIR /frontend

COPY package*.json ./
RUN npm install

# No need to copy source files since they will be mount as
# a volume for hot reloading in development

EXPOSE 5173

# Use development mode
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]