version: "3"

services:
  frontend:
    image: memora-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./:/frontend
      - /frontend/node_modules
    environment:
      - NODE_ENV=development
