stages:
  - test
  - build

test:
  stage: test
  image: node:20.6
  script:
    - npm install
    - echo "Running extremely simple test"
    - npm run test
    - echo "Test passed successfully!"

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest
